--- 

- hosts: localhost
  gather_facts: false
  
  tasks:
  - name: install GPG keys
    become: true
    apt_key: 
      url: "{{ item }}"
      state: present
    with_items:
      - https://download.sublimetext.com/sublimehq-pub.gpg
      - https://dl-ssl.google.com/linux/linux_signing_key.pub

  - name: add repository PPA's
    become: true
    apt_repository: 
      repo: "{{ item.name }}"
      filename: "{{ item.filename }}"
      state: present 
      update_cache: yes
    with_items:
      - { name: deb http://dl.google.com/linux/chrome/deb/ stable main, filename: google-chrome }
      - { name: "deb https://download.sublimetext.com/ apt/stable/", filename: sublime-text }
      - { name: ppa:gnumdk/lollypop, filename: lollypop }

  - name: update sources
    become: true
    command: apt update

  - name: Install a list of packages
    become: true
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - curl 
      - software-properties-common
      - apt-transport-https 
      - sshpass
      - httpie
      - nmap
      - maven
      - git
      - php
      - gnome-tweaks
      - openssh-server
      - ca-certificates
      - sublime-text
      - vim 
      - lollypop

     

